"""
Generate the three-tab CesiumJS dashboard (index / energy / ecology)
from a populated ``StudyArea`` + computed modules.

The viewer code is identical to the hand-coded HTMLs in the
``For Local Host`` / ``For Public`` / ``For Private`` folders of the
Twekkelerveld prototype. This module copies those HTML files (treated as
templates), writes the GeoJSON the dashboards expect, and emits a
``config.js`` so that the same HTML can be served from local files, a
Cloudflare R2 bucket, or a private host.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Optional

from ..privacy import PrivacyMode, apply_privacy
from ..study_area import StudyArea


# Default GeoJSON filename consumed by the CesiumJS dashboards. Matches
# `GEOJSON_FILE` in the public energy.html.
DEFAULT_BUILDINGS_GEOJSON = "twekkelerveld_buildings_energy_ageEUI_wgs84.geojson"


def write_config_js(
    out_dir: str | Path,
    r2_base: str = "",
    r2_prefix: str = "",
) -> Path:
    """
    Write a ``config.js`` next to the dashboard HTMLs.

    Parameters
    ----------
    out_dir : str | Path
        Directory where the dashboards will live.
    r2_base : str
        Public base URL (e.g. ``https://pub-xxx.r2.dev``). Empty string for
        purely local serving via Live Server.
    r2_prefix : str
        Optional path prefix appended to the base.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    js = (
        "// Generated by urbandt.viz.build_dashboard\n"
        "window.DT_CONFIG = {\n"
        f"  R2_BASE: {json.dumps(r2_base)},\n"
        f"  R2_PREFIX: {json.dumps(r2_prefix)}\n"
        "};\n"
    )
    p = out_dir / "config.js"
    p.write_text(js, encoding="utf-8")
    return p


def build_dashboard(
    area: StudyArea,
    out_dir: str | Path,
    mode: str | PrivacyMode = PrivacyMode.PUBLIC,
    energy=None,
    ecology=None,
    html_source_dir: Optional[str | Path] = None,
    geojson_name: str = DEFAULT_BUILDINGS_GEOJSON,
    r2_base: str = "",
    r2_prefix: str = "",
) -> dict:
    """
    Assemble the three-tab dashboard.

    Parameters
    ----------
    area : StudyArea
        Study area with energy/ecology indicators already attached.
    out_dir : str | Path
        Where to write the dashboard files.
    mode : str | PrivacyMode
        Which privacy filter to apply to the building GeoJSON.
    energy, ecology
        Currently unused (results live on ``area.buildings``); reserved.
    html_source_dir : str | Path, optional
        Folder containing the three template HTMLs (``index.html``,
        ``energy.html``, ``ecology.html``). If None, the function only writes
        the data outputs — useful when the HTML viewer is published separately.
    geojson_name : str
        Output GeoJSON filename (must match the ``GEOJSON_FILE`` constant in
        the energy HTML).
    r2_base, r2_prefix
        Forwarded to :func:`write_config_js`.

    Returns
    -------
    dict
        Paths of all files written, keyed by purpose.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. Filtered GeoJSON
    gdf = area.to_wgs84()
    gdf = apply_privacy(gdf, mode)
    geojson_path = out_dir / geojson_name
    gdf.to_file(str(geojson_path), driver="GeoJSON")

    # 2. config.js
    config_js = write_config_js(out_dir, r2_base=r2_base, r2_prefix=r2_prefix)

    # 3. HTML templates — copied verbatim (these are the hand-coded viewers).
    html_files = {}
    if html_source_dir is not None:
        html_source_dir = Path(html_source_dir)
        for name in ("index.html", "energy.html", "ecology.html"):
            src = html_source_dir / name
            if src.exists():
                dst = out_dir / name
                shutil.copy2(src, dst)
                html_files[name] = dst

    return {
        "geojson": geojson_path,
        "config_js": config_js,
        "html": html_files,
        "mode": str(PrivacyMode(mode) if isinstance(mode, str) else mode),
    }
